#  베이스 이미지 설정
FROM ubuntu:18.04

# Nginx 설치
RUN apt-get -y update && apt-get -y upgrade 
RUN apt-get -y install nginx

#  포트 지정
EXPOSE 80

# Web 콘텐츠 배치 - 첫 번째 빌드과정에서는 실행되지 않고 다음 빌드 때 실행
ONBUILD ADD website.tar /var/www/html/

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
